version: '3'
services:
  # Redis Service
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - my-network

  # Backend Service
  backend:
    build: ./backend
    container_name: backend-container
    networks:
      - my-network
    environment:
      - REDIS_URL=redis://redis:6379
      - FRONTEND_URI=http://localhost:5173
      - PORT = 3000
    ports:
      - "5173:5173"
    depends_on:
      - redis

  # Frontend Service
  frontend:
    build: ./frontend
    container_name: frontend-container
    networks:
      - my-network
    environment:
      - VITE_BACKEND_URL=http://localhost:3000
    ports:
      - "3000:3000"
    depends_on:
      - backend

networks:
  my-network:
    driver: bridge
